version: '3'

services:
  app:
    container_name: app
    image: golang:1.8-alpine
    working_dir: /go/src/app
    volumes:
      - ./app:/go/src/app
    command: go run main.go

# volumes:
# @link https://github.com/docker/docker/issues/30441